import React from "react";
import PlanDetail from "../PlanDetail/PlanDetail";
const DATA = {
  title: "Ejemplo 1",
  description: "Descripcion de Ejemplo",
  marketAnalisis: "Analisis de mercado de ejemplo",
  prices: "Precios de ejemplo",
  sales: "Ventas de ejemplo",
  marketingPlan: "Plan de marketing de ejemplo",
  time: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque facilisis fermentum ligula, ac sagittis velit. Sed neque sapien, maximus nec diam ut, rutrum sodales tortor. Vivamus sollicitudin nulla et lacus commodo, vitae aliquet augue porttitor. Integer at cursus arcu. Sed mattis sollicitudin sapien id dictum. Suspendisse potenti. Maecenas eget venenatis turpis, quis fringilla eros. Suspendisse potenti. Aliquam mattis sem vel mi vestibulum, a consequat velit vehicula. Sed orci metus, luctus in fermentum et, semper at metus. Sed rhoncus ante a eros ornare, sit amet facilisis odio suscipit. Fusce molestie tincidunt orci, id faucibus sem dapibus vel. Donec quis enim ut justo pellentesque porta. Nunc luctus fringilla nisl sit amet placerat. Etiam tempus tempor elit, molestie laoreet eros lobortis non. Vivamus convallis at velit vitae consequat.

  Donec at commodo elit. Donec non magna iaculis, tristique leo condimentum, tristique erat. Nullam orci diam, rhoncus dignissim sem in, euismod cursus mauris. In sollicitudin est est, ac congue diam commodo sit amet. Vivamus vitae quam ipsum. Nulla ac tincidunt sapien. Praesent ac felis non diam tempor aliquam sit amet sed nulla. In ultricies lorem at pellentesque posuere.
  
  Nulla facilisi. Sed non laoreet eros, a lobortis dui. Quisque fringilla posuere nulla, et tincidunt sapien mollis non. Morbi eget lobortis mi, eu tincidunt neque. Nunc eleifend metus vehicula magna sagittis semper. Nam id leo leo. Mauris tincidunt mi nec maximus lacinia.
  
  Nulla ac pharetra ipsum. Phasellus pulvinar velit id est porta dignissim. Nulla et dapibus lacus, vestibulum vehicula augue. Quisque aliquet ligula vel lacinia consectetur. Proin efficitur arcu ac urna eleifend, vitae suscipit nisi tempor. Morbi eget tortor dui. Aliquam erat volutpat. Proin sit amet fermentum diam, non laoreet purus. Maecenas tincidunt dignissim dui, non eleifend ipsum congue vitae. In hac habitasse platea dictumst. Donec et gravida augue, laoreet ornare mauris.
  
  Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec in fermentum metus. Sed maximus metus diam, id ultrices nunc consectetur nec. Aliquam a velit a mi molestie vulputate non at mi. Fusce cursus arcu eu pellentesque ultricies. Phasellus tristique feugiat dolor quis viverra. Maecenas quis ligula nec libero pharetra elementum. Proin euismod nulla dolor, id ultrices odio fringilla vel. Aliquam at tempor tortor. Nullam non dictum ante, id dictum nisi. Donec a mattis tellus. Maecenas vitae mauris non magna egestas tempor id ac sem. Sed ac velit eu elit aliquet cursus. Integer viverra nulla sit amet sollicitudin vehicula.
  
  Cras augue est, volutpat euismod luctus a, convallis vitae dolor. Donec id ligula et nisl mattis auctor sit amet ac lacus. Duis dictum mi vel massa molestie sagittis. Suspendisse potenti. Donec vel ipsum nulla. Phasellus eget commodo lacus, a egestas sem. Donec vitae tempus turpis. Sed auctor augue vel ante euismod, nec eleifend lacus condimentum.
  
  Mauris ligula tortor, ultrices ut libero interdum, aliquam viverra dolor. Quisque lobortis porta porta. Quisque eget pharetra felis. Maecenas consequat gravida posuere. Duis sed lobortis lectus. Cras ut finibus lacus. Suspendisse a diam sit amet neque mollis egestas non quis erat. Pellentesque nec lorem feugiat, blandit nisl ornare, egestas nulla. Donec mattis ac ipsum at facilisis. Ut suscipit egestas nunc ut porta. Sed lacinia diam quis ligula sagittis accumsan. Morbi fermentum nibh eget ante ultricies, quis tincidunt odio molestie.
  
  Maecenas fringilla tempus ornare. Fusce sit amet quam efficitur, sagittis elit et, porta odio. Vivamus diam sem, consequat vitae euismod in, porttitor et massa. Praesent volutpat pretium nibh et laoreet. Curabitur neque eros, mattis in condimentum id, fringilla non mauris. Ut imperdiet ante semper, facilisis neque non, suscipit arcu. Vestibulum in luctus lacus. Duis convallis vestibulum elit id finibus. In maximus lacus in ligula ornare dapibus. In hac habitasse platea dictumst.
  
  Donec ac nisl quam. Suspendisse non tempor odio. Suspendisse finibus purus nec suscipit ultricies. Nulla elementum lorem eu aliquet aliquet. Maecenas in scelerisque tellus, blandit vulputate enim. Phasellus laoreet mauris id nulla posuere luctus et non mi. Nunc eget lorem nec augue fermentum suscipit nec ut ante. Quisque libero ante, efficitur ut pretium nec, ullamcorper id nibh. Donec vitae ipsum vel dolor facilisis varius. Proin mollis nisi vitae enim laoreet facilisis. Vivamus quis mollis dolor. Fusce erat ligula, ultrices in pellentesque at, pellentesque placerat velit. Curabitur luctus erat non tortor tempus tempor nec in libero. Nullam risus lacus, scelerisque lobortis libero non, accumsan sagittis magna. Pellentesque vel sem imperdiet, sollicitudin ante commodo, lobortis eros. Mauris id urna eu est luctus mattis sed in ligula.
  
  Fusce facilisis, magna pretium posuere aliquet, felis mauris congue metus, lacinia finibus neque massa in augue. Mauris eu dignissim sapien. Mauris vitae sapien at ligula venenatis luctus ac et nunc. Pellentesque vitae sem rutrum, blandit mi nec, vestibulum elit. Sed eget ex in justo fermentum fermentum. Maecenas ut nisi vel enim laoreet feugiat nec sed enim. Vivamus ornare neque ut hendrerit maximus. Proin mollis mi quis ultricies facilisis. Fusce blandit, est eu vestibulum scelerisque, risus leo luctus turpis, sit amet rhoncus augue sapien id est. Sed sodales imperdiet lorem, vitae facilisis ante imperdiet et. Etiam luctus semper nisi, at feugiat augue ultricies id. Nam malesuada justo nec magna lacinia, quis pharetra augue dapibus. Donec aliquam euismod egestas. Suspendisse porttitor in leo sed cursus. Morbi convallis diam velit, vitae consequat lectus ultricies in. In faucibus elit et viverra dignissim.
  
  Maecenas at volutpat justo, et venenatis nisl. In maximus maximus pellentesque. Duis viverra eleifend dui, feugiat sodales nunc mattis nec. Ut ac accumsan augue. Mauris accumsan sem sit amet laoreet tristique. Donec interdum metus eget mi convallis malesuada. Duis vitae consectetur nisi. Mauris cursus urna lorem, ac convallis nisl rhoncus accumsan. Mauris tincidunt, lacus eu pretium tincidunt, est enim vestibulum libero, sit amet varius neque lorem id nunc. Morbi tempor tempus augue, et tincidunt libero feugiat at. Aenean vehicula eu sapien eget gravida. Phasellus convallis varius justo, vitae rutrum dolor volutpat mattis. Donec cursus bibendum ante sed fringilla. Maecenas sem est, fermentum maximus eros et, convallis ullamcorper arcu. Praesent in risus eu arcu maximus ultrices. Duis porttitor consectetur risus sit amet ultricies.
  
  In semper nec nisl vel porta. Morbi eu sodales ex. Sed et mattis justo. Nulla commodo, purus a finibus porta, libero diam cursus justo, nec molestie nibh augue eu tortor. Mauris non ipsum urna. Suspendisse rhoncus fermentum arcu quis tristique. Etiam aliquam lectus porta augue convallis condimentum. Nulla maximus mauris ex, mattis ultrices turpis fringilla quis. Aenean augue metus, iaculis non convallis quis, lobortis eu felis. Sed nisl quam, dictum et sollicitudin eu, scelerisque eu sapien. Morbi quis pulvinar ligula.
  
  Nam sodales, augue at ultrices convallis, leo sem blandit turpis, vitae varius justo sem ut massa. Etiam id dui orci. Fusce varius lorem eu semper pharetra. Donec at dolor dolor. Mauris nec blandit erat, et faucibus diam. Sed sit amet lacus eget arcu hendrerit suscipit. Suspendisse vel risus blandit, euismod tellus sed, tincidunt leo. Quisque porta pharetra metus facilisis tincidunt. Donec at tincidunt lorem. Aenean imperdiet velit at risus vehicula tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam pretium ultrices nisi, eget pellentesque elit. Aenean convallis ullamcorper congue. Duis consectetur porttitor aliquet. Cras leo mi, iaculis sed lacus eu, dictum consequat tellus. Phasellus nunc tortor, aliquam non placerat in, hendrerit ut est.
  
  Pellentesque fringilla pharetra augue, tempus venenatis nisi condimentum at. Cras tempus gravida elementum. Suspendisse volutpat nulla sit amet neque mattis, in feugiat quam efficitur. Maecenas ac condimentum augue. Nulla vitae augue non ipsum sollicitudin aliquet sit amet non urna. Proin vitae tempus ex. Nunc aliquam nibh et iaculis efficitur. Nullam fermentum turpis vel lacus interdum egestas. Fusce vitae tortor odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque malesuada vel libero vestibulum hendrerit. Etiam finibus felis id tortor facilisis faucibus. Integer leo purus, hendrerit id tellus non, convallis interdum erat. Morbi ac tortor ac neque accumsan vulputate eu in purus.
  
  Nam posuere vitae justo ac posuere. Praesent facilisis placerat tellus non hendrerit. Nam sed lacus neque. Curabitur facilisis ligula quis ipsum congue, ac tincidunt tellus ullamcorper. Nunc mollis molestie tortor sed hendrerit. Suspendisse laoreet et urna eu facilisis. Nullam ac leo varius, commodo dolor scelerisque, aliquet risus. Fusce in tortor placerat, mattis dolor sit amet, fringilla nunc. Etiam lectus velit, sagittis non ante et, pretium pharetra felis. Proin at dui massa. Nam sit amet egestas diam. Donec et lectus massa. Aenean eget tempor nunc, ut elementum felis. Donec vitae suscipit nulla, id auctor lacus. Sed vel lacinia orci.
  
  Morbi libero sem, blandit eu dolor et, ornare congue arcu. Quisque at rutrum augue, nec semper orci. Aliquam consequat risus sit amet tortor fermentum commodo. Cras rutrum sapien id dignissim fermentum. Suspendisse pretium consequat consequat. Fusce condimentum bibendum lorem eu facilisis. Morbi tincidunt neque id eros dictum, a placerat orci mattis. Nullam tincidunt libero vitae blandit porttitor. Cras suscipit risus leo, vel dignissim lectus sodales eget.
  
  Duis porttitor eros vitae quam viverra cursus. Nullam a commodo dui. Sed a felis nulla. Donec vitae neque faucibus, fermentum dui a, vestibulum tellus. Nulla non turpis efficitur, laoreet odio quis, congue diam. Integer quis odio mollis, venenatis dolor vitae, consequat magna. Aenean blandit, ligula vel luctus rhoncus, tellus felis hendrerit dolor, in dictum tortor mauris in urna. Etiam aliquam risus quis erat laoreet convallis. Nulla condimentum, urna eget eleifend varius, erat quam elementum nisl, ut fermentum odio erat vitae leo. Nam lacus lectus, volutpat ac imperdiet vitae, vulputate vitae est. Maecenas purus arcu, rhoncus non scelerisque ut, egestas quis urna. In consequat laoreet facilisis.
  
  Mauris eget malesuada est. Ut a tortor dolor. Sed vitae porttitor velit. Nam ullamcorper tincidunt libero, vitae tristique tellus tincidunt porta. Cras tempus, augue vel tempor blandit, felis nunc porttitor mi, dictum sodales mi neque sit amet ante. Suspendisse id lacus ut turpis ornare cursus. Suspendisse vitae ex nunc. Vestibulum fermentum leo nec eros efficitur ultrices vitae ut velit. Quisque ac eros nec eros rutrum luctus. Quisque viverra aliquam eros, non fringilla ligula hendrerit eget. Phasellus eget venenatis arcu. Nam egestas, sem eget placerat scelerisque, eros libero tincidunt turpis, non aliquet mi orci eu arcu. Nulla facilisi.
  
  Ut at velit tortor. Phasellus commodo lacus vitae tincidunt lacinia. Mauris velit felis, tempus sed quam vitae, faucibus aliquam augue. Suspendisse in ipsum vitae massa sagittis gravida. Aliquam vehicula iaculis risus, nec sagittis libero. Nulla bibendum orci nec enim pharetra hendrerit. Praesent blandit nulla augue, vel imperdiet dolor volutpat vel. Cras tincidunt vitae nisl in lacinia. Curabitur quis malesuada erat. Suspendisse nec orci in quam dapibus auctor sed sed odio. Pellentesque mollis massa eu eros malesuada, sed gravida ante semper. Duis bibendum metus at sem efficitur semper. Donec nec justo laoreet, posuere quam non, laoreet libero. Cras commodo justo vel feugiat rhoncus. Morbi auctor eros ut ullamcorper mollis. Aenean dictum odio sed libero lacinia ultrices.
  
  Duis vehicula mattis purus quis commodo. Proin dignissim neque eu ligula ultrices, eu mattis eros molestie. In dignissim ante vitae vehicula lacinia. Ut iaculis at leo id scelerisque. Quisque id risus ut tortor consectetur fringilla. Donec odio enim, euismod sit amet hendrerit in, hendrerit sed ipsum. Vestibulum tincidunt luctus lacus. Duis lacinia vitae dolor a bibendum. Sed et nunc quis risus ullamcorper pellentesque et feugiat massa. Vestibulum posuere placerat lorem, vel molestie neque malesuada id.
  
  In non gravida lacus. Nullam sollicitudin, lorem non ullamcorper condimentum, tellus metus fringilla urna, eu commodo elit enim id nulla. Praesent sed sem dapibus, rhoncus turpis a, vulputate mi. Duis eget consequat tortor. Quisque aliquam, sapien et venenatis sagittis, magna tortor convallis metus, sed aliquam nisi urna non quam. In et pharetra mauris. Curabitur ut nulla et nibh tristique varius eu rutrum eros. Sed eu auctor augue. Praesent id velit nec tortor mattis interdum ac non tortor. Cras ultricies mollis dui. Duis in nisl lectus. Aenean accumsan dolor quis diam tincidunt dignissim. Aenean dignissim, ante quis egestas imperdiet, mi lectus lacinia massa, sed lacinia ex felis id risus.
  Proin euismod ante purus, sed ultrices ex ultricies vel. Pellentesque interdum pulvinar urna lobortis finibus. Suspendisse eget mi finibus, euismod purus id, condimentum sapien. Vivamus sed malesuada odio. Curabitur commodo magna a lectus elementum ornare. Maecenas nec libero efficitur, efficitur tellus at, convallis nunc. Nullam ornare.`,
  riskAnalisis: "Análisis De mercado de ejemplo",
  input: {
    budget: 2000,
    age: 25,
    location: "Argentina",
    skills: "Programacion",
    teacher: "Elon Musk",
  },
};

const Example1 = () => {
  return (
    <>
      <PlanDetail response={DATA} />
    </>
  );
};

export default Example1;
